site_name: SEKOIA.IO Documentation
site_url: https://docs.sekoia.io
repo_url: https://github.com/SEKOIA-IO/documentation

nav:
  - Getting Started:
      - Overview: getting_started/index.md
      - First steps: getting_started/first_steps.md
      - Inviting users to join your community: getting_started/inviting_users_to_join_your_community.md
      - API Key creation: getting_started/apikey_creation.md
      - 2-Factors Authentication: getting_started/2fa.md
      - Search:
          - Dork Language: searching/dork.md
          - Querying Operation Center Events: searching/search_events.md
  - Operation Center:
      - Overview: operation_center/index.md
      - Dashboards: operation_center/threat_exposition.md
      - Integrations:
          - Overview: integrations/index.md
          - Transports:
              - Overview: integrations/transport/index.md
              - Rsyslog: integrations/transport/rsyslog.md
              - Logstash: integrations/transport/logstash.md
              - syslog-ng: integrations/transport/syslog-ng.md
              - Graylog: integrations/transport/graylog.md
              - HTTPS: integrations/transport/https.md
          - Cloud and SaaS:
              - AWS:
                  - CloudTrail: integrations/aws_cloudtrail.md
                  - Flow Logs: integrations/aws_flow_logs.md
              - Microsoft Azure:
                  - Azure Active Directory: integrations/azure_ad.md
                  - Azure Mysql: integrations/azure_mysql.md
                  - Azure Linux machines: integrations/azure_linux.md
                  - Azure Network Watcher: integrations/azure_network_watcher.md
                  - Azure Windows machines: integrations/azure_windows.md
              - Microsoft Office 365: integrations/o365.md
              - Cisco Umbrella:
                  - Proxy Logs: integrations/umbrella_proxy.md
                  - Ip Logs: integrations/umbrella_ip.md
                  - Dns Logs: integrations/umbrella_dns.md
          - OS:
              - Linux: integrations/linux.md
              - Auditbeat Linux: integrations/auditbeat_linux.md
              - Windows: integrations/windows.md
              - Log Insight Windows: integrations/log_insight_windows.md
          - Application:
              - Alsid: integrations/alsid.md
              - Apache: integrations/apache.md
              - BIND: integrations/bind.md
              - Checkpoint: integrations/checkpoint.md
              - Cisco: integrations/cisco_asa.md
              - F5 BigIP: integrations/f5-big-ip.md
              - FortiGate: integrations/fortigate.md
              - FortiMail: integrations/fortimail.md
              - FortiWeb: integrations/fortiweb.md
              - FortiProxy: integrations/fortiproxy.md
              - HAProxy: integrations/haproxy.md
              - HarfangLab: integrations/harfanglab.md
              - ISC DHCP: integrations/dhcpd.md
              - NetFilter: integrations/netfilter.md
              - Nginx: integrations/nginx.md
              - OpenSSH: integrations/openssh.md
              - PaloAlto: integrations/paloalto.md
              - Postfix: integrations/postfix.md
              - Pulse Connect Secure: integrations/pulse.md
              - Sophos: integrations/sophos.md
              - SpamAssassin: integrations/spamassassin.md
              - Squid: integrations/squid.md
              - Suricata: integrations/suricata.md
              - Unbound: integrations/unbound.md
              - Zeek: integrations/zeek.md
          - Generic:
              - Common Event Format: integrations/cef.md
      - Configure:
          - Entities: operation_center/entities.md
          - Intakes: operation_center/intakes.md
          - Assets: operation_center/assets.md
      - Detect:
          - Rules Catalog: operation_center/rules_catalog.md
      - Investigate:
          - Alerts: operation_center/alerts.md
          - Events: operation_center/events.md
          - Cases: operation_center/cases.md
      - Automate:
          - Overview: operation_center/playbook_overview.md
          - Triggers: operation_center/triggers.md
          - Operators: operation_center/operators.md
          - Actions: operation_center/actions.md
      - FAQ: operation_center/faq.md
  - Intelligence Center:
      - Overview: intelligence_center/index.md
      - Data Model: intelligence_center/data_model.md
      - API: intelligence_center/api.md
      - External Integrations: intelligence_center/integrations.md
      - Web Application:
          - Dashboards: intelligence_center/dashboard.md
          - Graph Explorations: intelligence_center/graph_explorations.md
          - Observables: intelligence_center/observables.md
          - Data Export: intelligence_center/data_export.md
  - API Documentation:
      - overview: apis/index.md
      - Identity & authentication: apis/identity_&_authentication.md
  - What’s New?: releases
  - Support: https://support.sekoia.io

api:
  - name: Identity & authentication
    description: 'Manage authentication: password change, manage multi factor authentication and APIKeys.'
    url: identity_&_authentication
  - name: Profile & permissions
    description: Manage rights within a community (members, roles, permissions, etc.).
    url: profile_&_permissions
  - name: Dashboards
    description: 'Allows user to define and manage their dashboards (Operation Center & Intelligence Center)'
    url: dashboard
  - name: Notifications
    description: Manage notification rules and in-app notifications
    url: notifications
  - name: 'Operation Center: Rules, Entities, Intakes, Events'
    description: Configure the detection and remediation service offered by SEKOIA Operation Center.
    url: 'operation_center:_rules,_entities,_intakes,_events'
  - name: 'Operation Center: Alerts & Case Management'
    description: 'Manage alerts raised by SEKOIA.IO Operation Center.'
    url: 'operation_center:_alerts_&_case_management'
  - name: 'Operation Center: Asset Management'
    description: 'Manage your sensitive assets'
    url: 'operation_center_asset_management'
  - name: 'Intelligence Center: Cyber Threat Intelligence Database'
    description: 'Manage your collections of Threat Intelligence materials.'
    url: 'intelligence_center:_cyber_threat_intelligence_database'
  - name: 'Intelligence Center: Enrichment'
    description: 'API to manage enrichments'
    url: 'intelligence_center:_enrichment'
  - name: 'Automation: Symphony Orchestrator'
    description: 'Manage your orchestration Playbooks.'
    url: 'automation:_symphony_orchestrator'
  - name: 'Partners'
    description: 'Allows partner to push their configurations'
    url: 'partners'
  - name: 'Ingest: Manage and test event parsers'
    description: 'API manage parsers'
    url: 'ingest:_manage_and_test_event_parsers'
  - name: 'Operations Center: Events API'
    description: 'Operations Center: Events API'
    url: 'operations_center:_events_api'

theme:
  custom_dir: theme
  name: material
  logo: assets/sekoiaio.svg
  favicon: assets/favicon.ico
  include_search_page: true
  search_index_only: false
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.top
  font:
    text: Open Sans

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/sekoia_fr

copyright: Copyright 2021 SEKOIA. All rights reserved.

extra_css:
  - stylesheets/sekoiaio.css
extra_javascript:
  - javascript/sekoiaio.js
markdown_extensions:
  - admonition
  - attr_list
  - codehilite
  - pymdownx.details
  - pymdownx.highlight:
      linenums: true
      linenums_style: pymdownx-inline
  - pymdownx.superfences
  - pymdownx.tabbed

plugins:
  - redoc